### ISSUE TITLE
reconsider dir-based approach

### ISSUE THREAD

**Issue by tjjfvi** [paritytech/trun#5]
Right now trun bases what it runs simply on the ts files in a directory. However, in certain cases our examples aren't simply in this structure – for example, capi has some nested examples like `examples/dynamic/balance.ts`.

I'd suggest instead adopting an approach like `deno test` and recursively searching based on a file extension. In `scale-ts` we've adopted a [convention of `.eg.ts` files](https://github.com/paritytech/scale-ts/tree/main/examples) for examples – perhaps we should adopt the same convention in Capi, and build trun around this.

**Comment by ryanleecode** [comment]
that approach can work. another approach is letting them supply a glob pattern and trun searches based on that.

**Comment by tjjfvi** [comment]
In that case, the glob pattern can default to `**/*.eg.ts`

**Comment by ryanleecode** [comment]
For the `.ignore` file should the contents now be a list of globs rather than just file names? Filter flag would also be a glob now i'd imagine.
